// flow-typed signature: c204c7a1d65b14ca6449bee1f0095fdd
// flow-typed version: <<STUB>>/system-ui_v^1.0.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'system-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'system-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'system-ui/index' {
  declare module.exports: $Exports<'system-ui'>;
}
declare module 'system-ui/index.js' {
  declare module.exports: $Exports<'system-ui'>;
}
