// flow-typed signature: fde5538bff579649e4e39dc4c20dd5fc
// flow-typed version: <<STUB>>/tachyons_v^4.9.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tachyons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tachyons' {
  declare module.exports: any;
}
