import { createActions } from 'redux-actions';

export default createActions(
  'GET_TRANSACTIONS',
  'LOAD_TRANSACTIONS_FROM_CACHE',
  'LOAD_TRANSACTIONS_FROM_CACHE_FAILED',
  'FETCH_TRANSACTIONS',
  'LOAD_TRANSACTIONS_SUCCESS',
  'LOAD_TRANSACTIONS_FAILED',
  'INVALIDATE_TRANSACTIONS_CACHE',
  { namespace: '/TRANSACTIONS/' }
);
